services:
  mongodb:
    image: mongo:6
    container_name: airq-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    volumes:
    - ./output:/app/output
    tty: true
    stdin_open: true
    container_name: airq-app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
    entrypoint: ["python"]

volumes:
  mongo_data:
